### PR TITLE
Solid Colour Version

### PR DESCRIPTION
**Pull request by stefenfriesen**
Added a solid colour option to the SVG. Bubbles have been divided from the liquid path for transparency.

### CODE REVIEW

**Comment by parkr** [comment]
I'd prefer it if you created a new file. :)

**Comment by stefenfriesen** [comment]
I obviously don't know what I'm doing when it comes to GitHub. Bear with me.

**Comment by stefenfriesen** [comment]
Scrapped the repository and started over. I don't need to waste everyone's time while I learn how to use GitHub. Closing this PR and submitting a new one.

**Comment by parkr** [comment]
That's cool! Take your time. Let me know how I can help. You should be able to clone, branch, add, commit, and push:

```bash
~$ git clone git@github.com:stefenfriesen/brand.git
~$ cd brand
~/brand$ git checkout -b black-logo
~/brand$ # add your files to the folder
~/brand$ git add jekyll-logo-black.svg jekyll-logo-black.png
~/brand$ git commit -m "Add black version of Jekyll logo."
~/brand$ git push origin black-logo
```

Then you should see a `Create Pull Request` button on https://github.com/jekyll/brand. :)

**Pull request closed without merging**
